# Generated by Django 6.0 on 2025-12-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
